---
Name: mysite
---
SSViewer:
  theme: 'giltrap'
MySQLDatabase:
  connection_charset: 'utf8'
Filesystem:
  file_create_mask: 02777
  folder_create_mask: 02777
---
Name: myextensions
---
FormField:
  extensions:
    - FieldExtension
Image:
  extensions:
    - ContentImageExtension
---
Name: blockmanaber
---
BlockManager:
  themes:
    giltrap:
      areas:
        #Sidebar: true # a Sidebar area will be available on all page types in simple theme
        HeroBlocks:
        LowerTallBlock:
        LowerBlocks:
          only: HomePage # a BeforeContent area will be available only on HomePage page types in simple theme
        #AfterContent:
          #except: HomePage # a AfterContent area will be available on all page types except HomePage in simple theme
        #Footer: true